detect_obj:
  ros__parameters:
    tuning_mode: true # Could set this here but leave it off so it can be easily set by the launch script
    x_min: 0
    x_max: 100
    y_min: 15
    y_max: 100
    h_min: 20
    h_max: 40
    s_min: 40
    s_max: 255
    v_min: 0
    v_max: 255
    sz_min: 0
    sz_max: 55

detect_obj_3d:
  ros__parameters:
    h_fov: 0.62831853
    obj_radius: 0.032
    camera_frame: "camera_link_optical"

follow_obj:
  ros__parameters:
    rcv_timeout_secs: 10.0
    angular_chase_multiplier: 0.7
    forward_chase_speed: 0.1
    search_angular_speed: 0.5
    max_size_thresh: 0.22
    filter_value: 0.5