joy_node:
  ros__parameters:
    device_id:
    deadzone:
    autorepeat:

teleop_node:
  ros_parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_linear:
      y: 0
    scale_linear:
      y: 0.5
    scale_linear_turbo:
      y: 1.0
      
    