<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="prefix" default="base" />
    <xacro:property name="base_length" value="0.256" />
    <xacro:property name="base_width" value="0.1" />
    <xacro:property name="base_height" value="0.05" />
    <xacro:property name="base_mass" value="1.366" />
    <xacro:include filename="$(find robo_cart_description)/urdf/mecanum_wheel.xacro" />

    <link name="base_footprint_link" />

    <joint name="base_footprint_base_joint" type="fixed">
        <parent link="base_footprint_link" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${wheel_radius}" />
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}"
            z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <xacro:mecanum_wheel prefix="$(arg prefix)" side="front_right" x_reflect="1" y_reflect="-1" />

    <xacro:mecanum_wheel prefix="$(arg prefix)" side="front_left" x_reflect="1" y_reflect="1" />

    <xacro:mecanum_wheel prefix="$(arg prefix)" side="rear_right" x_reflect="-1" y_reflect="-1" />

    <xacro:mecanum_wheel prefix="$(arg prefix)" side="rear_left" x_reflect="-1" y_reflect="1" />

</robot>