<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="load_camera" params="base_length base_height use_gazebo">
        <joint name="base_camera_joint" type="fixed">
            <parent link="base_link" />
            <child link="camera_link" />
            <origin xyz="${base_length / 2.0 + 0.009} 0 ${base_height + 0.02 + 0.015}" rpy="0 0.18 0" />
        </joint>
        <link name="camera_link">
            <visual>
                <geometry>
                    <box size="0.018 0.0685 0.0405" />
                </geometry>
                <material name="orange" />
            </visual>
            <collision>
                <geometry>
                    <box size="0.018 0.0685 0.0405" />
                </geometry>
            </collision>
        </link>
        <joint name="camera_optical_joint" type="fixed">
            <parent link="camera_link" />
            <child link="camera_link_optical" />
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        </joint>
        <link name="camera_link_optical" />
        <xacro:if value="${use_gazebo}">
            <gazebo reference="camera_link">
                <material>
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.1 1</diffuse>
                    <specular>0.1 0.1 0.1 1</specular>
                </material>
                <sensor name="camera" type="camera">
                    <camera name="usb camera">
                        <camera_info_topic>/camera/camera_info</camera_info_topic>
                        <horizontal_fov>0.62831853</horizontal_fov>
                        <image>
                            <width>640</width>
                            <height>480</height>
                        </image>
                        <clip>
                            <near>0.05</near>
                            <far>1.5</far>
                        </clip>
                    </camera>
                    <always_on>true</always_on>
                    <gz_frame_id>camera_link_optical</gz_frame_id>
                    <topic>/camera/image_raw</topic>
                    <update_rate>2</update_rate>
                    <visualize>true</visualize>
                </sensor>
            </gazebo>
        </xacro:if>
    </xacro:macro>
</robot>