<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo>
        <plugin name="gz::sim::systems::MecanumDrive" filename="libgz-sim8-mecanum-drive-system">

            <!-- https://gazebosim.org/api/sim/9/classgz_1_1sim_1_1systems_1_1MecanumDrive.html -->

            <front_left_joint>base_front_left_wheel_joint</front_left_joint><!-- Name of a joint that controls a front left
            wheel. This element can
            appear multiple times, and must appear at least once -->

            <front_right_joint>base_front_right_wheel_joint</front_right_joint><!-- Name of a joint that controls a front right
            wheel. This element can
            appear multiple times, and must appear at least once -->

            <back_left_joint>base_rear_left_wheel_joint</back_left_joint><!-- Name of a joint that controls a back left wheel.
            This element can
            appear multiple times, and must appear at least once -->

            <back_right_joint>base_rear_right_wheel_joint</back_right_joint><!-- Name of a joint that controls a back right
            wheel. This element can
            appear multiple times, and must appear at least once -->

            <wheelbase>${base_length / 2.0}</wheelbase><!-- Longitudinal distance between front and back wheels, in
            meters. This
            element is optional, although it is recommended to be included with an appropriate
            value. The default value is 1.0m -->

            <wheel_separation>${base_width + wheel_length}</wheel_separation><!-- Lateral distance between left and right
            wheels, in meters. This
            element is optional, although it is recommended to be included with an appropriate
            value. The default value is 1.0m -->

            <wheel_radius>${wheel_radius}</wheel_radius><!-- Wheel radius in meters. This element is optional,
            although it is
            recommended to be included with an appropriate value. The default value is 0.2m -->

            <odom_publish_frequency></odom_publish_frequency><!-- Odometry publication frequency.
            This element is optional, and
            the default value is 50Hz -->

            <topic></topic><!-- : Custom topic that this system will subscribe to in order to
            receive command
            velocity messages. This element if optional, and the default value is
            /model/{name_of_model}/cmd_vel -->

            <odom_topic></odom_topic><!-- Custom topic on which this system will publish odometry
            messages. This
            element if optional, and the default value is /model/{name_of_model}/odometry -->

            <tf_topic></tf_topic><!-- Custom topic on which this system will publish the transform
            from frame_id
            to child_frame_id. This element if optional, and the default value is
            /model/{name_of_model}/tf -->

            <frame_id></frame_id><!-- Custom frame_id field that this system will use as the origin
            of the odometry transform in both the <tf_topic> gz.msgs.Pose_V message and the
            <odom_topic> gz.msgs.Odometry message. This element if optional, and the default value
            is {name_of_model}/odom -->

            <child_frame_id></child_frame_id><!-- Custom child_frame_id that this system will use as
            the target of the odometry trasnform in both the <tf_topic> gz.msgs.Pose_V message and
            the <odom_topic> gz.msgs.Odometry message. This element if optional, and the default
            value is {name_of_model}/{name_of_link} -->

        </plugin>
    </gazebo>
</robot>