<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo>
        <plugin name="gz::sim::systems::MecanumDrive" filename="libgz-sim8-mecanum-drive-system">

            <front_left_joint>base_front_left_wheel_joint</front_left_joint>
            <front_right_joint>base_front_right_wheel_joint</front_right_joint>
            <back_left_joint>base_rear_left_wheel_joint</back_left_joint>
            <back_right_joint>base_rear_right_wheel_joint</back_right_joint>
            <wheelbase>${base_length / 2.0}</wheelbase>
            <wheel_separation>${base_width + wheel_length}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

        </plugin>
    </gazebo>
</robot>