<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="load_gazebo_sim_ros2_control_plugin"
        params="use_gazebo base_length base_width wheel_radius wheel_width">
        <xacro:if value="${use_gazebo}">
            <gazebo>
                <plugin filename="libgz_ros2_control-system"
                    name="gz_ros2_control::GazeboSimROS2ControlPlugin">
                    <parameters>$(find robo_cart_description)/config/ros2_controllers.yaml</parameters>
                    <ros>
                        <remapping>/controller_manager/robot_description:=/robot_description</remapping>
                    </ros>
                </plugin>
                <plugin name="gz::sim::systems::MecanumDrive"
                    filename="libgz-sim8-mecanum-drive-system">
                    <front_left_joint>base_front_left_wheel_joint</front_left_joint>
                    <front_right_joint>base_front_right_wheel_joint</front_right_joint>
                    <back_left_joint>base_rear_left_wheel_joint</back_left_joint>
                    <back_right_joint>base_rear_right_wheel_joint</back_right_joint>
                    <wheelbase>${base_length / 2.0}</wheelbase>
                    <wheel_separation>${base_width + wheel_width}</wheel_separation>
                    <wheel_radius>${wheel_radius}</wheel_radius>
                    <odom_publish_frequency>50.0</odom_publish_frequency>
                    <topic>/mecanum_drive_controller/cmd_vel</topic>
                    <odom_topic>/model/robo_cart/odometry</odom_topic>
                    <tf_topic>/model/robo_cart/tf</tf_topic>
                    <frame_id>odom</frame_id>
                    <child_frame_id>base_footprint_link</child_frame_id>
                </plugin>
                <plugin name="gz::sim::systems::OdometryPublisher"
                    filename="libgz-sim8-odometry-publisher-system">
                    <odom_publish_frequency>50.0</odom_publish_frequency>
                    <robot_base_frame>base_footprint_link</robot_base_frame>
                </plugin>
                <plugin name="gz::sim::systems::JointStatePublisher"
                    filename="libgz-sim8-joint-state-publisher-system" />
            </gazebo>
        </xacro:if>
    </xacro:macro>
</robot>