<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="load_lidar" params="base_length base_height use_gazebo">
        <joint name="base_laser_frame_joint" type="fixed">
            <parent link="base_link" />
            <child link="laser_frame" />
            <origin xyz="${base_length / 4.0} 0 ${base_height + 0.055}" rpy="0 0 0" />
        </joint>
        <link name="laser_frame">
            <visual>
                <origin xyz="0.0 -0.004 0.0" rpy="0.0 0.0 ${-M_PI}" />
                <geometry>
                    <mesh filename="file://$(find robo_cart_description)/meshes/X3_Lidar.stl"
                        scale="0.001 0.001 0.001" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.032" length="0.018" />
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.020" r="0.032" l="0.018" o_xyz="0 0 0" o_rpy="0 0 0" />
        </link>
        <xacro:if value="${use_gazebo}">
            <gazebo reference="laser_frame">
                <material>
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.1 1</diffuse>
                    <specular>0.1 0.1 0.1 1</specular>
                </material>
                <sensor name="laser" type="gpu_lidar">
                    <pose relative_to="laser_frame"> 0 0 0 0 0 0 </pose>
                    <gz_frame_id>laser_frame</gz_frame_id>
                    <topic>scan</topic>
                    <update_rate>10</update_rate>
                    <always_on>true</always_on>
                    <visualize>true</visualize>
                    <lidar>
                        <scan>
                            <horizontal>
                                <samples>360</samples>
                                <resolution>1</resolution>
                                <min_angle>-3.14159</min_angle>
                                <max_angle>3.14159</max_angle>
                            </horizontal>
                            <vertical>
                                <samples>1</samples>
                                <resolution>1</resolution>
                                <min_angle>0</min_angle>
                                <max_angle>0</max_angle>
                            </vertical>
                        </scan>
                        <range>
                            <min>0.20</min>
                            <max>30.0</max>
                            <resolution>0.013</resolution>
                        </range>
                    </lidar>
                </sensor>
            </gazebo>
        </xacro:if>
    </xacro:macro>
</robot>